# Generated by Django 5.0.2 on 2024-02-26 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dependencia', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_reserva', models.TimeField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aura.equipo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aura.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aura.sala'),
        ),
    ]
